sudo: required

services:
  - docker

language: go
go:
  - 1.8.3

env:
  global:
    - IMAGE_TAG=patrickdappollonio/terraform-gendocs

install:
  - # empty to avoid getting dependencies

script:
  - make ci
  - docker run -it $IMAGE_TAG /bin/sh -c "terraform-gendocs -h"

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push $IMAGE_TAG;
    fi
